# Generated by Django 4.0 on 2022-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'verbose_name': 'Товары и заказы', 'verbose_name_plural': 'Товары и заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время оформления заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_out',
            field=models.DateTimeField(null=True, verbose_name='Время получения заказа'),
        ),
    ]
