# Generated by Django 4.0 on 2022-04-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0006_category_name_en_category_name_ru_post_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authorUser_en',
            field=models.OneToOneField(help_text='author name', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='author',
            name='authorUser_ru',
            field=models.OneToOneField(help_text='author name', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Имя автора'),
        ),
    ]
