# Generated by Django 4.0 on 2022-04-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0007_author_authoruser_en_author_authoruser_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authorUser',
            field=models.OneToOneField(help_text='имя автора', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorUser_en',
            field=models.OneToOneField(help_text='имя автора', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorUser_ru',
            field=models.OneToOneField(help_text='имя автора', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Новости'), ('AR', 'Статья')], default='AR', help_text='название категории', max_length=2, verbose_name='Категория'),
        ),
    ]
