# Generated by Django 4.0 on 2022-03-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Записаться на приём', 'verbose_name_plural': 'Записаться на приём'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Имя клиента'),
        ),
    ]
