# Generated by Django 4.0 on 2022-03-31 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(verbose_name='Сообщение клиента'),
        ),
    ]
